In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/startup_valuation_dataset.csv")

In [2]:
df["unicorn"] = (
    df["estimated_valuation_usd"] >= 1_000_000_000
).astype(int)

In [3]:
df["unicorn"].value_counts()

unicorn
1    38675
0    11325
Name: count, dtype: int64

In [4]:
df.drop(
    columns=["estimated_valuation_usd"],
    inplace=True
)

In [5]:
df.isnull().sum()

startup_id                   0
startup_name                 0
founded_year                 0
country                      0
region                       0
industry                     0
funding_round                0
funding_amount_usd           0
funding_date                 0
lead_investor                0
co_investors                 0
employee_count               0
estimated_revenue_usd        0
exited                       0
exit_type                45100
tags                         0
unicorn                      0
dtype: int64

In [6]:
df.columns.tolist()

['startup_id',
 'startup_name',
 'founded_year',
 'country',
 'region',
 'industry',
 'funding_round',
 'funding_amount_usd',
 'funding_date',
 'lead_investor',
 'co_investors',
 'employee_count',
 'estimated_revenue_usd',
 'exited',
 'exit_type',
 'tags',
 'unicorn']

In [7]:
for col in df.select_dtypes(include="object"):
    print(col, df[col].nunique())

startup_id 50000
startup_name 36866
country 243
region 6
industry 7
funding_round 7
funding_date 3653
lead_investor 7
co_investors 259
exit_type 2
tags 18644

In [8]:
df.isnull().sum()

df.columns.tolist()

for col in df.select_dtypes(include="object"):
    print(col, df[col].nunique())

startup_id 50000
startup_name 36866
country 243
region 6
industry 7
funding_round 7
funding_date 3653
lead_investor 7
co_investors 259
exit_type 2
tags 18644

In [9]:
df.drop(
    columns=[
        "startup_id",
        "startup_name"
    ],
    inplace=True
)

In [10]:
df["funding_date"].head()

0    2020-03-15
1    2017-04-09
2    2015-09-09
3    2018-10-15
4    2020-01-12
Name: funding_date, dtype: object

In [11]:
df["funding_date"] = pd.to_datetime(
    df["funding_date"]
)

In [12]:
df["funding_year"] = df["funding_date"].dt.year

df["funding_month"] = df["funding_date"].dt.month

In [13]:
df.drop(
    columns=["funding_date"],
    inplace=True
)

In [14]:
CURRENT_YEAR = 2026

df["startup_age"] = (
    CURRENT_YEAR -
    df["founded_year"]
)

In [15]:
df["investor_count"] = (
    df["co_investors"]
    .fillna("")
    .apply(
        lambda x: len(str(x).split(","))
    )
)

In [16]:
df.drop(
    columns=["co_investors"],
    inplace=True
)

In [17]:
df.drop(
    columns=["tags"],
    inplace=True
)

In [18]:
df.isnull().sum()

founded_year                 0
country                      0
region                       0
industry                     0
funding_round                0
funding_amount_usd           0
lead_investor                0
employee_count               0
estimated_revenue_usd        0
exited                       0
exit_type                45100
unicorn                      0
funding_year                 0
funding_month                0
startup_age                  0
investor_count               0
dtype: int64

In [19]:
df["exit_type"].value_counts(dropna=False)

exit_type
NaN            45100
IPO             2529
Acquisition     2371
Name: count, dtype: int64

In [20]:
df["exit_type"] = df["exit_type"].fillna("No Exit")

In [21]:
df["exit_type"].value_counts()

exit_type
No Exit        45100
IPO             2529
Acquisition     2371
Name: count, dtype: int64

In [22]:
df.drop(
    columns=[
        "exited",
        "exit_type"
    ],
    inplace=True
)

In [23]:
num_cols = [
    "funding_amount_usd",
    "employee_count",
    "estimated_revenue_usd"
]

for col in num_cols:
    print(col)
    print(df[col].skew())
    print()

funding_amount_usd
8.60692768301686

employee_count
-0.005165298392917885

estimated_revenue_usd
10.23356780168963

In [24]:
import numpy as np

df["funding_amount_usd"] = np.log1p(
    df["funding_amount_usd"]
)

df["estimated_revenue_usd"] = np.log1p(
    df["estimated_revenue_usd"]
)

In [25]:
for col in [
    "funding_amount_usd",
    "estimated_revenue_usd"
]:
    print(col)
    print(df[col].skew())
    print()

funding_amount_usd
-0.0013731396711437627

estimated_revenue_usd
-0.0821577050897747

In [26]:
cat_cols = df.select_dtypes(include="object").columns.tolist()

print(cat_cols)

['country', 'region', 'industry', 'funding_round', 'lead_investor']

In [27]:
for col in cat_cols:
    print(f"\n{col}")
    print(df[col].nunique())

country
243

region
6

industry
7

funding_round
7

lead_investor
7

In [28]:
country_freq = df["country"].value_counts(normalize=True)

df["country_freq"] = df["country"].map(
    country_freq
)

In [29]:
df[["country","country_freq"]].head()

             country  country_freq
0             Latvia       0.00426
1             Guyana       0.00360
2         Uzbekistan       0.00434
3  Equatorial Guinea       0.00394
4          Lithuania       0.00386

In [30]:
df.drop(
    columns=["country"],
    inplace=True
)

In [31]:
df = pd.get_dummies(
    df,
    columns=[
        "region",
        "industry",
        "funding_round",
        "lead_investor"
    ],
    drop_first=True
)

In [32]:
df.shape

(50000, 33)

In [33]:
df.head()

,founded_year,funding_amount_usd,employee_count,estimated_revenue_usd,unicorn,funding_year,funding_month,startup_age,investor_count,country_freq,...,funding_round_Series A,funding_round_Series B,funding_round_Series C,funding_round_Series D,lead_investor_Andreessen Horowitz,lead_investor_Index Ventures,lead_investor_Sequoia,lead_investor_SoftBank,lead_investor_Tiger Global,lead_investor_Y Combinator
0,2008,20.454141,106,19.484970,1,2020,3,18,1,0.00426,...,True,False,False,False,False,False,True,False,False,False
1,2006,19.755663,735,17.637135,1,2017,4,20,3,0.00360,...,True,False,False,False,False,False,False,False,True,False
2,2010,21.644890,346,18.819120,1,2015,9,16,1,0.00434,...,True,False,False,False,False,False,True,False,False,False
3,2013,20.751934,302,19.895324,1,2018,10,13,2,0.00394,...,False,True,False,False,False,False,False,False,False,False
4,2012,19.397995,286,17.720862,1,2020,1,14,1,0.00386,...,False,False,False,True,False,True,False,False,False,False

In [34]:
df.to_csv(
    "processed_startup_data.csv",
    index=False
)

print("Processed dataset saved.")

Processed dataset saved.

#

In [35]:
country_freq.head(20)

country
Congo                         0.00858
Korea                         0.00756
United Kingdom                0.00500
Slovakia (Slovak Republic)    0.00480
Iraq                          0.00478
Lesotho                       0.00476
Norfolk Island                0.00474
United Arab Emirates          0.00470
British Virgin Islands        0.00470
Bangladesh                    0.00468
Cameroon                      0.00464
Paraguay                      0.00464
Spain                         0.00462
Vietnam                       0.00460
El Salvador                   0.00460
Mayotte                       0.00458
Canada                        0.00456
Bosnia and Herzegovina        0.00452
Costa Rica                    0.00452
Ghana                         0.00452
Name: proportion, dtype: float64